language: python

python:
    - "2.7"

#installing dependencies
install:
    - pip2 install -r requirements.txt

#running the tests
script:
    - cd src/chamster_backend
    - python2 manage.py test core/tests/

